version: '3.8'

services:
  application:
    image: ${IMAGE_NAME:-ghcr.io/owner/repo:latest}
    container_name: ndgl-application-dev
    ports:
      - "5080:8080"
    env_file: .env
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    name: backend-network
    external: true
